---
title: "Regular Expression - Examples"
author: "Asmik & Lisa - for Intro to NLP"
date: "2 April 2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r setup_packages, message=FALSE}
# Load required packages

library("stringr")
```

# Identify

```{r identify_1}
str_detect(string  = "Cote d'Azur", 
           pattern = "\'")
```

```{r identify_2}
str_detect(string  = c("nlp_2021", "nlppp_2021"), 
           pattern = "p{3}")
```

```{r identify_3}
# Add \\ for special characters 
str_detect(string  = c("never.stop.learning", "never stop learning.."), 
           pattern = "\\.{2}")
```


# Extract

Matches at most 1 times:

```{r extract_1}
str_extract(string = c("n", "nlp", "nllp", "nllllp"), 
            pattern = "nl?p")
```

Matches at least 2 times:

```{r extract_2}
str_extract(string = c("n", "nlp", "nllp", "nllllp"), 
            pattern = "nl{2,}p")
```

Matches between 1 and 2 times:

```{r extract_3}
str_extract(string = c("n", "nlp", "nllp", "nllllp"), 
            pattern = "nl{1,2}p")
```

# Locate

Any digit:

```{r locate_1}

str_locate(pattern = "\\d",
           string  = c("nlp2021", "nlp_kurs"))
```

Digits of any length:

```{r locate_2}
str_locate(pattern = "\\d+",
           string  = c("nlp2021", "nlp_kurs"))
```

Any alphanumeric:

```{r locate_3}
str_locate(pattern = "\\w",
           string  = c("nlp2021", "nlp_kurs"))
```

Any alphanumeric of any length:

```{r locate_4}
str_locate(pattern = "\\w+",
           string  = c("nlp2021", "nlp_kurs"))
```

# Replace

Matches the start of the string: 

```{r replace_1}

str_replace(string      = c("abcdef", "cdabef", "abefcd"), 
            pattern     = "^cd", 
            replacement = "_")

```

Matches the end of the string: 

```{r replace_2}
str_replace(string      = c("abcdef", "cdabef", "abefcd"), 
            pattern     = "cd$", 
            replacement = "_")
```

Matches any location of the string: 

```{r replace_3}
str_replace(string      = c("abcdef", "cdabef", "abefcd"), 
            pattern     = "cd", 
            replacement = "_")
```


