---
title: "Scraping Twitter Data - Example"
author: "Asmik & Lisa - for Intro to NLP"
date: "2 April 2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Setup 
consumer_key <- "wc37jEDaiiNxcmj7Ot8nS7U2u"
consumer_secret <- "BlEbL1Wd96EKh1Kgonrp7StJD8L7mbcZ736R00S3EFTclaTdU0"
access_token <- "1244208984724209665-GWNgwnJnPdFIIgV9X8Gio07Re8w82v"
access_secret <- "CJC9BtdlNpv6GIGovENTMDQUgjWzLljyp4WYepreo7xpF"
```


```{r setup_packages, message=FALSE}
# Load required packages

library("rtweet")
library("tidytext")
library("tidyverse")
```

# Set up API access

```{r cars}

create_token(
  consumer_key = consumer_key,
  consumer_secret = consumer_secret,
  access_token = access_token,
  access_secret = access_secret)

```
# Extract

Search for tweets with hashtag *merkel*:

```{r title}
scraped_tweets_merkel <- search_tweets(
  "#merkel", # i.e. "": match exact phrase, # hashtag, @ at mentions)
  n = 1000,
  lang = "de", # Account language set
  include_rts = FALSE, # Exclude retweets
  type = "recent" # i.e. "popular"
  )
scraped_tweets_merkel$query <- "Merkel"

```

Search for tweets with hashtag *AfD*:

```{r title_1}
scraped_tweets_afd <- search_tweets(
  "#AfD", # i.e. "": match exact phrase, # hashtag, @ at mentions)
  n = 1000,
  lang = "de", # Account language set
  include_rts = FALSE, # Exclude retweets
  type = "recent" # i.e. "popular"
)
scraped_tweets_afd$query <- "AfD"
```

Combine both:

```{r year}
combined_tweets <- rbind(scraped_tweets_merkel, scraped_tweets_afd)
```

Multiple independent search queries: 

```{r year_1}
tweets_multiple <- Map(
  "search_tweets",
  c("afd", "corona OR merkel"),
  n = 100,
  lang = "de"
)

# bind by row 
tweets_multiple_df <- do_call_rbind(tweets_multiple) 

head(tweets_multiple_df)

```

# Explore

Tweets' timeline: Frequency of tweets over time: 

```{r year_clean}
summary(combined_tweets$created_at)
```

```{r rank}
combined_tweets %>%
  dplyr::group_by(query) %>%
  rtweet::ts_plot( "hours", cex = 0.8) +
  labs(x = NULL, y = NULL,
       title = "Frequency of tweets",
       subtitle = paste0(format(min(combined_tweets$created_at), "%d %B %Y"), " to ", format(max(combined_tweets$created_at),"%d %B %Y")),
       caption = "Data collected from Twitter's REST API via rtweet") +
  theme_minimal() 
```

Most retweeted tweet: 

```{r rank_1}
most_retweeted_tweet <- combined_tweets %>% 
  arrange(-retweet_count) %>%
  slice(1) %>% 
  select(created_at, screen_name, text, retweet_count, status_id)

print(most_retweeted_tweet$text)
```

Top hashtags: 

```{r rank_clean}

combined_tweets %>% 
  unnest_tokens(hashtag, text, "tweets", to_lower = FALSE) %>%
  filter(str_detect(hashtag, "^#"),
         hashtag != "#Merkel", 
         hashtag != "#AfD") %>%
  count(hashtag, sort = TRUE) %>%
  top_n(5)

```

